### ISSUE TITLE
Editeur de textes : Ajout information

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#100]
Si l’utilisateur essaie d’ouvrir un document Word en le sélectionnant depuis son disque dur (comme un PDF) plutôt que via un copier-coller, alors il devrait être informé que les documents Word doivent être ouverts dans Libre Office puis qu’il doit faire un copier-coller. Il faut éventuellement lui préciser par une copie d’écran comment faire son copier-coller (s’il est nécessaire d’utiliser l’icône « Coller depuis Word » de l’éditeur WYSIWYG).  Environnement : Si l’utilisateur essaie d’ouvrir un document Word en le sélectionnant depuis son disque dur (comme un PDF) plutôt que via un copier-coller, alors il devrait être informé que les documents Word doivent être ouverts dans Libre Office puis qu’il doit faire un copier-coller. Il faut éventuellement lui préciser par une copie d’écran comment faire son copier-coller (s’il est nécessaire d’utiliser l’icône « Coller depuis Word » de l’éditeur WYSIWYG).

**Comment by rkouifi** [comment]
A clôturer
