### ISSUE TITLE
Editeur de textes : image et curseur de la souris

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#105]
L’utilisateur ouvre un fichier PDF, qui s’affiche dans l’éditeur. Lorsque sa souris se trouve au-dessus d’une image, le bouton « Sélectionner » devrait s’activer automatiquement (et se désactiver à la sortie) et le curseur de la souris devrait lui suggérer qu’il peut sélectionner un rectangle.  Environnement : L’utilisateur ouvre un fichier PDF, qui s’affiche dans l’éditeur. Lorsque sa souris se trouve au-dessus d’une image, le bouton « Sélectionner » devrait s’activer automatiquement (et se désactiver à la sortie) et le curseur de la souris devrait lui suggérer qu’il peut sélectionner un rectangle.

**Comment by rkouifi** [comment]
A clôturer
