### ISSUE TITLE
Editeur de textes : emplacement de l'image initial

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#106]
Lorsque j’ai découpé un bloc, son emplacement d’origine dans l’image devrait être grisé pour mieux faire comprendre l’absence du bloc qui a été découpé.
Lorsque j’ai découpé un bloc, son emplacement d’origine dans l’image devrait être grisé pour mieux faire comprendre l’absence du bloc qui a été découpé.

**Comment by rkouifi** [comment]
A clôturer
