### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#170]
Les messages sont affichés en minuscules sur un fond non hachés. Ils doivent rester affichés suffisamment longtemps pour que l'utilisateur puisse les voir.  Environnement :

**Comment by rkouifi** [comment]
A traiter dans le cadre su sprint utilisabilité

**Comment by Marithe17** [comment]
Texte vert sur fond vert (non accessible AA)

**Comment by rkouifi** [comment]
Messages accessibles sur fond blanc et bordure verte checkbox verte
