### ISSUE TITLE
Document adapté : Règles de document sans sommaire

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#180]
Un document ne contenant que des éléments au style « Paragraphe » (aucun titre) ou ne contenant qu’un seul paragraphe avec un style de titre devrait s’afficher sans sommaire. Le sommaire ne devrait s’afficher que dès qu’il y a au moins 2 paragraphes avec un style de titrage.

**Comment by rkouifi** [comment]
A remplacer par #510 
A archiver
