### ISSUE TITLE
retour à la liste des profils

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#260]
Le contexte : je termine de modifier le dernier profil de ma liste des profils. Je l’enregistre.
Ce à quoi je m’attends : retourner à la liste des profils et voir d’un seul coup d’œil l’aperçu du profil que je viens de modifier (le dernier de cette liste), donc mon navigateur est automatiquement positionné sur ce profil et non sur le haute de page
Ce que j’observe : mon navigateur affiche la liste des profils depuis le haut de la page, sans ancrage sur le profil récemment modifié.

**Comment by rkouifi** [comment]
Déjà fait.
