### ISSUE TITLE
L'interface d'AccessiDys n'est pas adaptée à la résolution de l'écran

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#263]
Contexte : Nous avons effectué une démo d'AccessiDys en utilisant un écran (probablement 24 pouces)
Ce qu'on attend : L'interface d'AccessiDys s'adapte à la résolution de l'écran
Ce qu'on observe : Obligé de scroller pour accéder à des informations à droite

**Comment by rkouifi** [comment]
Remplacé par #580 
A archiver
