### ISSUE TITLE
Synthèse vocale : Message explicatif

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#269]
Affichage document adapté : quand j'ouvre un document adapté en consultation,
Un  message s'affiche m'expliquant comment lancer la synthèse vocale avec possibilité de cocher le bouton "Ne plus afficher" afin de ne plus afficher ce message pour les prochaines sélections sur la page courante (si l'utilisateur ouvre un nouveau document alors le message s'affiche lors de la première sélection).
Ce message s'affiche si les conditions suivantes sont réunies :
1) la synthèse vocale est activée
2) le navigateur supporte la synthèse vocale.

NB : Ce message est à mettre à jour quand le mode de sélection de texte sera amélioré (texte blanc sur fond bleu est perturbateur pour certaines personnes dys)  Environnement :

**Comment by rkouifi** [comment]
Idem que #549 
A archiver
