### ISSUE TITLE
style nommés règles ou format

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#274]
Le contexte : je passe de l’éditeur à la gestion d’un profil.
Ce à quoi je m’attends : dans l’éditeur, les styles s’appellent « styles », c’est le nom du menu déroulant y donnant accès ; et dans la gestion du profil, ils s’appellent également styles.
Ce que je constate : dans l’éditeur, le menu s’appelle « format » ; dans le gestionnaire de profils, ils s’appellent règles. 

Agrandir les boutons de la liste déroulante "Styles" ==> Exemple : paragraphe

**Comment by rkouifi** [comment]
Env. d'intégration : Dans l'éditeur de textes, le menu déroulant contient toujours "format". A remplacer par "Styles" avec infobulle "Styles"

**Comment by Marithe17** [comment]
Environnement intégration PC / Google Chrome / Firefoxe
Dans éditeur  toujours "Format" niveau mais "style" dans la liste déroulante et info bulle
