### ISSUE TITLE
ordre des styles dans l'aperçu des profils

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#275]
Le contexte : je suis sur la liste des profils, avec leur aperçu
Ce à quoi je m’attends : dans chaque aperçu de profil, les styles devraient apparaître dans le même ordre, celui également utilisé dans le menu des styles dans l’éditeur. Egalement le même ordre dans la popin de modif de profil.
Ce que j’observe : le style par défaut présente son style « Titre 1 » en avant-dernier et le style « Sous-titre 2 » à la fin.

**Comment by rkouifi** [comment]
Bug déjà réglé.
