### ISSUE TITLE
"Chargement de vos documents en cours"

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#280]
Je me connecte à Cned-Adapt, affichage du message "Chargement de vos documents en cours". Impossible d’accéder à mes documents.

Piste : Est-il possible d'afficher un message plus explicite en cas d'erreur
Exemple d'erreur :
"Votre compte Cned-Adapt n'est plus associé à celui de DropBox. Veuillez autoriser cette association"
"Votre document n'est plus stocké dans Dropbox"
....
  Environnement : Production

**Comment by rkouifi** [comment]
N'est plus d'actualité après la mise en place de #551 
A archiver
