### ISSUE TITLE
Profil : Aperçu _ Ajouter un bouton « fermer » qui permet de revenir à la liste des profils

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#421]
Profil : Aperçu
Ajouter un bouton « fermer » qui permet de fermer l'interface de l'aperçu et  revenir à la liste des profils  Environnement :

**Comment by rkouifi** [comment]
l'interface de l'aperçu sera supprimé (voir #476).
Cette histoire est à archiver.
