### ISSUE TITLE
Document partagé : le profil actuel n'est pas visible

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#447]
BUG DE RÉGRESSION

Contexte : Je partage un document via Email
Ce que j'observe : Afficher le document partagé en cliquant sur le lien reçu par email. Le profil actuel est invisible.
Ce que j'attend : Afficher le document partagé en cliquant sur le lien reçu par email avec la possibilité d'accéder au profil actuel contenant les profils par défaut déclarés dans l'administration.  Environnement : Recette et prod

**Comment by rkouifi** [comment]
Non reproductible
