### ISSUE TITLE
US 4162: Remplacer Cned-Adapt par Accessidys

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#450]
En tant qu'utilisateur

Je peux voir dans l'environnement de prod le remplacement de CNED-ADAPT par Accessidys

Afin de pouvoir savoir que le nom de l'application a changé

=================================================
1) Il faudra commencer par l'environnement de recette avant de la basculer en prod
2) Le nouveau logo de l'application vous sera fourni par le Cned
3) Lister l'ensembles des endroits où il faudra remplacer CNED-ADAPT par AccessiDys (interface, liens url, les adresses email)
4) Un nom de domaine www.accessidys.com (.fr, ....) va être crée pour remplacer adapt.cned.fr
5) cned-adapt2.cned.fr doit être remplacé par accessidys.org/recette  OU recette.accessidys.org ;
6) Dans toute la documentation : Remplacer CNED-ADAPT par AccessiDys
  Environnement :

**Comment by rkouifi** [comment]
A archiver
