### ISSUE TITLE
Impossible de partager un profil par mail

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#457]
Environnement : https://cned-adapt2.cned.fr/#/
Navigateur : Chrome, Firefox, IE

Actions réalisées :
Création d'un profil
Partager le profil par mail

Résultat observé :
Impossible de partager le profil par mail, l'écran indique : Partage du profil en cours. Veuillez patienter .. de façon indéfini.
Le destinataire ne reçoit par le mail.  Environnement :

**Comment by rkouifi** [comment]
**A tester après la réalisation de #461**  avant de la mettre dans le backlog sprint
