### ISSUE TITLE
Impossible de déléguer un profil

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#463]
Environnement : Recette
Navigateur :
Google Chrome : Version 47.0.2526.111 m
Internet Explorer : Version 10.0.9200.17607
FireFox : 42.0
Support : PC
Mode : Connecté

Actions réalisées :
- Suppression des historiques
- Création d'un nouvel utilisateur (testajo024.05.06.2016@yopmail.com)
- Création d'un nouveau profil
- Délégation du profil (testajo023.05.06.2016@yopmail.com)

Résultat observé :
ERREUR LORS DE L'ENVOI DE LA DEMANDE.

(Reproduit sur IE10, Chrome, Firefox)
  Environnement :

**Comment by rkouifi** [comment]
A retester après l'ajout d'email
