### ISSUE TITLE
Application mise "Hors connexion" alors que la connexion est activée

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#464]
**A faire avec #425** 
Environnement : Recette
Navigateur :
Google Chrome : Version 47.0.2526.111 m
Internet Explorer : Version 10.0.9200.17607
FireFox : 42.0
Support : PC
Mode : Connecté

Actions réalisées :
- Connexion à l'application sur les 3 navigateurs
- Navigation diverse sur l'application

Résultat observé :
Après qlq minutes d'inactivité (pas plus de 5 minutes), l'application passe en mode Hors connexion, sans raison particulière.  Environnement :

**Comment by rkouifi** [comment]
A retester avant de mettre dans le backlog sprint
