### ISSUE TITLE
Profils _ IHM modifier les styles : mauvais positionnement du cadre du texte de démo et les 2 derniers champs

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#474]
Gestion des profils
Dans l'interface "Modifier les valeurs de styles ..", le cadre du texte de démonstration est positionnée en bas et à droite de l'interface. IL devrait être positionné comme dans la version précédente à savoir en haut à droite de l'interface.
D'autre part, les champs "Espace entre les mots" et "Espace entre les caractères" sont décalés par rapport aux autres champs.  Environnement : recette/prod

**Comment by Marithe17** [comment]
Environnement intégration PC/Google Chrome/Firefoxe
OK
