### ISSUE TITLE
Profils : Supprimer l'action "Aperçu"

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#476]
A partir de la liste des profils, je clique sur "le picto Action" puis  "Aperçu".
Ce que je constate :  accéder à l'action Aperçu
Ce que j'attends : ne pas accéder à l'action Aperçu

**Comment by rkouifi** [comment]
Environnement de recette : Profils ==> Le bouton "Aperçu" n'existe plus.

**Comment by Marithe17** [comment]
Environnement -intégration : Profils --> Le bouton "Aperçu" n'existe plus.
