### ISSUE TITLE
Aperçu des profils différent d'un navigateur à un autre

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#480]
Environnement : Recette
Navigateur :
Google Chrome : Version 47.0.2526.111 m
FireFox : 42.0
Support : PC

Mode : Connecté
Contexte : PROFIL

Actions réalisées :
- Suppression des historiques
- Création d'un nouveau compte (testajo029.19.06.2016@yopmail.com // CnedAjo2016)
- Affichage de la page des profils

Résultat observé :
Entre firefox et Chrome, il y a une différence d'affichage des profils.
Sur chrome, on ne voit qu'une ou deux ligne pour chaque aperçu de style, sur firefox on en voit plus de 5 lignes.

CF : Screen.  Environnement :

**Comment by rkouifi** [comment]
A tester après la #265 avant de mettre dans le backolog sprint

**Comment by rkouifi** [comment]
l'aperçu sera supprimé.
Plus d'actualité
