### ISSUE TITLE
Impossible de renommer un document HL pour chrome

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#485]
Environnement : Recette
Navigateur :
Google Chrome : Version 47.0.2526.111 m
FireFox : 42.0
Support : PC
Mode : HL
Contexte : Modifier titre de document

Actions réalisées :
- Désactivation de la connexion
- Création d'un document
- Enregistrement du document
- Modification du titre du document

Résultat observé :
Impossible de renommer le document, la page bloque sur le message suivant :
Renommage de votre document en cours. Veuillez patienter... loader  Environnement :

**Comment by rkouifi** [comment]
A restester

**Comment by rkouifi** [comment]
A clôturer
