### ISSUE TITLE
Impossible de créer un profil HL avec Firefox

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#486]
Environnement : Recette
Navigateur :
FireFox : 42.0
Support : PC
Mode : HL
Contexte : Création d'un profil

Actions réalisées :
- Désactivation de la connexion
- Création d'un profil

Résultat observé :
La liste des styles n'apparaît pas/
CF : Screen  Environnement :

**Comment by rkouifi** [comment]
A clôturer
