### ISSUE TITLE
[PROD]Logo déformé lors de la connexion à dropbox pendant l'inscription

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#487]
Environnement : PROD
Navigateur :
Google Chrome : Version 47.0.2526.111 m
FireFox 42
Support : PC
Mode : Connecté

Contexte : Création de compte

Actions réalisées :
- Création d'un nouvel utilisateur

Résultat observé :
Le logo est déformé lors de la connexion à dropbox pendant l'inscription.

cf : screen  Environnement :

**Comment by rkouifi** [comment]
Plus d'actualité après la mise en place #551 
A archiver
