### ISSUE TITLE
[PROD] Impossible d'ouvrir un document en mode HL avec IE11

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#490]
Environnement : PROD
Navigateur : IE 11
Support : PC

Mode : Hors ligne

Contexte : Import de document en mode déconnecté

Actions réalisées :
- Connexion à l'application
- Deconnexion du réseau
- Dans Document, cliquer sur Ajout de document
- Cliquer sur Ouvrir un document
- Selectionner un PDF, PNG, EPUB ou JPG, puis valider

Résultat observé :
Affichage de l'éditeur de document vide.
Seul le nom du document apparaît.

CF : PJ
  Environnement :

**Comment by rkouifi** [comment]
A restester

**Comment by rkouifi** [comment]
A clôturer
