### ISSUE TITLE
Affichage des profils trop long

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#491]
Environnement : PROD
Navigateur : IE 11
Support : PC

Mode : Hors ligne

Contexte : Affichage du profil en mode déconnecté

Actions réalisées :
- Connexion à l'application
- Déconnexion du réseau
- Affichage de la page page profils

Résultat observé :
L'affichage des profils est trop long.

CF : PJ
  Environnement :

**Comment by rkouifi** [comment]
A traiter dans le cadre du sprint "Performance"
