### ISSUE TITLE
[PROD] Impossible de renommer un document en mode HL avec IE11

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#494]
Environnement : PROD
Navigateur : IE 11
Support : PC

Mode : Hors ligne

Contexte : Renommage de document en mode déconnecté

Actions réalisées :
- Connexion à l'application
- Deconnexion du réseau
- Affichage de la liste des documents
- Renommer un document

Résultat observé :
Impossible de renommer un document, affichage du message :
Renommage de votre document en cours. Veuillez patienter...

(J'ai attendu + de 5 mn
CF : Screen  Environnement :

**Comment by rkouifi** [comment]
Non reproductible

**Comment by rkouifi** [comment]
A clôturer
