### ISSUE TITLE
Éditeur de textes: styles non prises en compte

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#498]
*Contexte *: Dans l'éditeur de textes, j'ajoute un document, je saisis du texte suivant :
Titre 1: Démonstration.
Sous-titre 1: Démonstration.
Titre 2: Démonstration.
Sous-titre 2: Démonstration.
Titre 3: Démonstration.
Titre 4: Démonstration.
Paragraphe: Démonstration.
....

Puis j'affecte les styles.

*Ce que je constate* : Tous les styles  (pieds de page, légende, entête de page, citation, annotation, sous-titre 1, sous-titre 2) ne sont pris en compte et ont comme affectation "Format" une fois je passe à une autre ligne
*Ce que je dois avoir *: prise en compte de ces styles dans l'éditeur de texte.  Environnement : production

**Comment by rkouifi** [comment]
Non reproductible
