### ISSUE TITLE
bug profils mal associés au compte

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#503]
Le contexte : l’utilisateur s’authentifie et dispose de plusieurs comptes utilisateurs, puis il se déconnecte (ou ferme et re-ouvre son navigateur ?) et ouvre le lien d’un document sans s’authentifier (anonymement)
Ce à quoi je m’attends : je ne vois que les profils prévus par l’administrateur pour le mode anonyme/non authentifié
Ce que j’observe : je vois parmi les profils des profils de mon compte authentifié  Environnement : Recette/prod

**Comment by DI-access** [comment]
Bug non reproduit
