### ISSUE TITLE
affichage de page de taille volumineuse : page blanche pas de message d'attente

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#508]
Contexte : avec le compte "direction-innovation@cned.f", je consulte l'aperçu du document de Mme Bovary.
Ce que j'observe : page blanche (ou souris figée)
Ce que j'attends : Affichage du message d'attente puis celui du document adapté en fonction du profil actuel.  Environnement : Recette/ Production
Chargement progressif ?

**Comment by rkouifi** [comment]
A traiter dans le cadre du sprint de performance
