### ISSUE TITLE
Adaptation de page adaptée

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#512]
·         Contexte : je suis authentifié et j’affiche un document qui est donc adapté selon mon profil, je clique sur la bookmarlet
·         Ce à quoi je m’attends : je m’attends à ce que la page se recharge à l’identique : même document, même URL, même authentification et profil
·         Ce que je constate : il se passe des trucs bizarres

Remarque, de même :
·         Contexte : je suis authentifié et j’ajoute, via l’éditeur, un lien hypertexte vers un autre document Accessidys (par exemple un lien que j’ai reçu en partage), puis j’enregistre mon document et je l’affiche en mode adapté. Je vois le lien cliquable, je clique dessus.
·         Ce à quoi je m’attends : je m’attends à rester sur mon serveur Accessidys, avec mon authentification et mon profil actuel, et à voir cet autre document Accessidys en mode adapté
·         Ce que je constate : pour l’instant, rien, mais vérifier qu’il ne se passe rien d’autre
  Environnement :

**Comment by rkouifi** [comment]
A préciser le document pour reproduire le bug.
