### ISSUE TITLE
code en anglais

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#513]
·         Contexte : je suis développeur anglophone et je veux corriger un bug dans le code. J’ouvre le code
·         Ce à quoi je m’attends : les noms des variables, fonctions, etc. sont en anglais et non en français (et respectent les conventions de style Javascript, cf JSLINT)
·         Ce que je constate : de nombreux noms sont en français
   Environnement :

**Comment by rkouifi** [comment]
Déjà traité 
Un commentaire en anglais a été ajouté pour expliquer les variables, fonctions...
