### ISSUE TITLE
amélioration de l'utilisabilité : revue des messages

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#514]
·         Contexte : je suis utilisateur, des messages s'affichent pour diverses raisons
·         Ce à quoi je m’attends : les messages de l’application sont écrits en français clair et simple et compréhensible par le commun des mortels
·         Ce que je constate : certains messages sont ambigus (cf. audits d’utilisabilité)  Environnement :

**Comment by rkouifi** [comment]
A traiter dans le cadre du sprint "Utilisabilité"
