### ISSUE TITLE
Faille de sécurité sur AccessiDys

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#517]
X-Account-Key:	account26
X-UIDL:	UID91596-1167946620
X-Mozilla-Status:	0001
X-Mozilla-Status2:	00000000
X-Mozilla-Keys:
X-Spam-Checker-Version:	SpamAssassin 3.4.0 (2014-02-07) on village005.cyberbrain.net
X-Spam-Level:
X-Spam-Status:	No, score=0.7 required=5.0 tests=HTML_IMAGE_ONLY_24, HTML_MESSAGE,RCVD_IN_DNSWL_NONE,RCVD_IN_MSPIKE_H3,RCVD_IN_MSPIKE_WL, RP_MATCHES_RCVD,SPF_PASS,T_DKIM_INVALID,URIBL_BLOCKED autolearn=no autolearn_force=no version=3.4.0
Delivered-To:	sig@akasig.org
Return-Path:	<bounces+848413-39db-sig=akasig.org@sgmail.github.com>
Received:	from o8.sgmail.github.com (o8.sgmail.github.com [::ffff:167.89.101.199]) (TLS: TLSv1/SSLv3,128bits,DHE-RSA-AES128-GCM-SHA256) by village005.cyberbrain.net with ESMTPS; Sun, 18 Sep 2016 20:27:51 +0200 id 0000000000041DD2.0000000057DEDCA7.00000AB7
DKIM-Signature:	v=1; a=rsa-sha1; c=relaxed; d=github.com; h=from:reply-to:to:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; s=s20150108; bh=AykPmyw39zkIUeyUif0eNltA9GY=; b=RgnlnIOgyitEvPSg DmYkaIHerl0HBVCeaybrZdfz64FctRFjKGb35YCFOJR19oamVYFYxR9CFGiFLMrO kezB+xSIPfQ5VUUVBD9q7HgHLD1ewqxiXBIfmDMI3hXHEuqdaRwI11LkhHi6VeEQ 0owTtqwNaY+gQb+SIc9phzH9/OQ=
Received:	by filter0496p1mdw1.sendgrid.net with SMTP id filter0496p1mdw1.29042.57DEDC6F17 2016-09-18 18:26:55.311037225 +0000 UTC
Received:	from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16]) by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id FY_tUD1nTTSQ5l4wOYiYQg for <sig@akasig.org>; Sun, 18 Sep 2016 18:26:55.118 +0000 (UTC)
Date:	Sun, 18 Sep 2016 11:26:54 -0700
From:	ryarnyah <notifications@github.com>
Reply-To:	cnedDI/AccessiDys <reply+000a2e745441d709ac30427616635f68b8fae9718d4d617692cf0000000113f69e6e92a169ce0a96fe94@reply.github.com>
To:	cnedDI/AccessiDys <AccessiDys@noreply.github.com>
Message-ID:	<cnedDI/AccessiDys/issues/4@github.com>
Subject:	[cnedDI/AccessiDys] [Security] Command injection vulnerability on /textToSpeech (#4)
Mime-Version:	1.0
Content-Type:	multipart/alternative; boundary="--==_mimepart_57dedc6ef2ed6_cc893f87d1e432a02431b9"; charset=UTF-8
Content-Transfer-Encoding:	7bit
Precedence:	list
X-GitHub-Sender:	ryarnyah
X-GitHub-Recipient:	Siggg
List-ID:	cnedDI/AccessiDys <AccessiDys.cnedDI.github.com>
List-Archive:	https://github.com/cnedDI/AccessiDys
List-Post:	<mailto:reply+000a2e745441d709ac30427616635f68b8fae9718d4d617692cf0000000113f69e6e92a169ce0a96fe94@reply.github.com>
List-Unsubscribe:	<mailto:unsub+000a2e745441d709ac30427616635f68b8fae9718d4d617692cf0000000113f69e6e92a169ce0a96fe94@reply.github.com>, <https://github.com/notifications/unsubscribe/AAoudLzEwVpzlAk_HbqaxmG7MMDEbUL4ks5qrYJugaJpZM4J_-SK>
X-Auto-Response-Suppress:	All
X-GitHub-Recipient-Address:	sig@akasig.org
X-SG-EID:	5osButQ5l4D9hANa8wiH8DkEc6fSz82WlNOlpuNgQuwoXjtXfg9c4DY/lSNvHKT+t8xAeir67JRSpn 49DgbgkcdSAlX7SHu7mlsaNV2dHpNRXclC3dQ7S33V8dXC8rcnnxAN5AEHDToOF+60C5SuUretzf3+ B5vemEouektRg9mti7B+z/S0+f3hvSVMHC3uFOoWYGX9uzsn0fZ/n7ZKEw==

An logged user can execute any command on server (https://www.owasp.org/index.php/Command_Injection).
Example: Imagine you have a user who has a local.token equal to "XXXXXXXXX" (can get it from /login)
You can actually execute any command like that:
curl -X POST "[http://]http://<server>/textToSpeech" --data 'id=XXXXXXXXX&text=";<command to execute>; #'  Environnement : production

**Comment by rkouifi** [comment]
A clôturer
