### ISSUE TITLE
supprimer les comptes accessidys

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#518]
Le problème : l’inscription sur Accessidys est peu utilisable car il faut créer un compte accessidys et se lier à un compte dropbox (ou autre) voire le créer, ce qui est compliqué.
·         La solution :
o   Supprimer la notion de compte AccessiDys pour ne conserver que les comptes Dropbox (ou autre fournisseur cloud), ne stocker aucune donnée utilisateur sur les serveurs accessidys
o   Ne rendre l’authentification cloud (dropbox) nécessaire qu’au moment où l’utilisateur veut « sauvegarder » son profil et ses documents
o   Si jamais l’utilisateur clique sur partager (ou déléguer) ses profils ou ses documents, alors lui indiquer qu’il doit d’abord les « sauvegarder » pour pouvoir faire cela.
o   Tant que les profils et documents ne sont pas sauvegardés, alerter visuellement l’utilisateur sur le fait que les documents ne sont pas sauvegardés

Tant que les profils et documents ne sont pas « sauvegardés », ils sont tout de même « enregistrés » dans le cache du navigateur et donc modifiables.

Ainsi l’appli est 100% utilisable, sauf partage et délégation, sans compte utilisateur d’aucune sorte. Tout reste stocké dans le navigateur de l’utilisateur. Et ce n’est qu’au moment où l’utilisateur comprend qu’il a besoin de sauvegarder ses données qu’une authentification a lieu, et uniquement l’authentification nécessaire, c’est-à-dire celle sur un fournisseur de cloud privé.  Environnement :

**Comment by rkouifi** [comment]
N'est plus d'actualité après la mise en place de #551
