### ISSUE TITLE
Architecture applicative avec Dropbox

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#519]
Nous avons besoin de ne pas montrer d’URL Accessidys/CNED pour chaque document mais de montrer plutôt des URL de clouds, pour diminuer les probabilités d’attaque juridique par des ayants droits,

- Les docs sur Dropbox seraient remis avec un HTML complet (tags d’entêtes, etc.) et inclueraient un script de redirection équivalent à un clic sur la bookmarklet
- Lors de l’affichage d’un document par AccessiDys, si le doc vient de Dropbox, alors l’URL dans la barre d’adresse est ré-écrite par un code JS faisant appel à l’API HTML5 qui est faite pour cela (cela se fait sans rafraîchissement du document).

**Comment by rkouifi** [comment]
En rapport avec #506

**Comment by rkouifi** [comment]
A clôturer
