### ISSUE TITLE
Remplacer  l’API Dropbox v.1 qui va expirer en juin 2017

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#520]
remplacement de l’API Dropbox v.1 par la V2 ou une autre API de cloud privé.
Nb : Etude de faisabilité avant toute action  Environnement :

**Comment by rkouifi** [comment]
**WITTY**
FrontEnd (AngularJs) :
Modification des Url
Modification des méthodes http
Modification des appels (ajout des nouveaux headers HTTP)
Prise en compte des nouvelles structures de données des API -> Impact des fonctions de mapping de l’application

BackEnd :
Aucun impact pour le moment. L’authentification sera délocalisée dans le frontEnd lors de la refonte de la création de compte (voir  #551  ).
