### ISSUE TITLE
Annotation button only visible in "page mode"

### ISSUE THREAD

**Issue by Siggg** [AccessiDys/AccessiDys#524]
* Context : I am reading a document with accessidys
* What I expect : to see the annotation button in the menu on the right whether I am in "page" mode or default mode
* What I observe : the annotation button is not visible in the default mode ; it only becomes visible once I push the "mode page" button.

**Comment by Marithe17** [comment]
Environnement  intégration PC / Google Chrome / Firefoxe =>Annotation ok sur les 2 modes

Le menu  "Navigation documents " (menu Wrapper) 
                                --> en Scrollant ce menu remonte et devient fixe au niveau du picto sommaire
Si je modifie un doc - > je me retrouve dans éditeur de texte -> 
           En aperçu  -> ce que je vois -> un autre menu 
                             -> ce que j'attends -> le même menu

**Comment by rkouifi** [comment]
Problème d'affichage d'image
Pb de menu à droite (on ne voit pas les premiers les icones quand on scrolle)
