### ISSUE TITLE
Can't add a new style in my profil

### ISSUE THREAD

**Issue by Siggg** [AccessiDys/AccessiDys#525]
* Context : I am in the profile manager, I am modifying an existing profile (Sophie's profile), I see the list of existing styles in this profile, I want to add a new style (e.g. "Titre 2")
* What I expect : I expect to see a "Add a new style" link or button
* What I obseve : I don't see any and don't know how to add a new style.

**Comment by rkouifi** [comment]
This problem exists with the profiles created with the former IHM.

**Comment by rkouifi** [comment]
Archivé
