### ISSUE TITLE
Éditeur de textes : Affichage de documents après enregistrement

### ISSUE THREAD

**Issue by DI-access** [AccessiDys/AccessiDys#526]
Contexte : j'ai crée un document à partir de l'éditeur de textes. Après enregistrement, j'ai fermé le document puis je suis allé vérifier sa présence dans la liste des documents
Ce que j’attends : Apparition du document dans la liste des documents
Ce que je constate : Pas de document

NB : Dans Dropbox, le document existe bien

**Comment by rkouifi** [comment]
N'est plus d'actualité
A archiver
