### ISSUE TITLE
Configuration de l'application avec les informations du proxy

### ISSUE THREAD

**Issue by DI-access** [AccessiDys/AccessiDys#528]
Après l'installation d'AccessiDys dans un serveur 'Académie de Guyane), j'ai essayé de créer un compte AccessiDys. L'association de ce compte avec celui de Dropbox ne fonctionne pas ==> affichage du message suivant :

InternalOAuthError: failed to obtain access token at /appli/CNED/git/accessidys/node_modules/passport-dropbox-oauth2/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth2.js:125:38 at /appli/CNED/git/accessidys/node_modules/passport-dropbox-oauth2/node_modules/passport-oauth/node_modules/oauth/lib/oauth2.js:177:18 at ClientRequest.<anonymous> (/appli/CNED/git/accessidys/node_modules/passport-dropbox-oauth2/node_modules/passport-oauth/node_modules/oauth/lib/oauth2.js:148:5) at emitOne (events.js:77:13) at ClientRequest.emit (events.js:169:7) at TLSSocket.socketErrorListener (_http_client.js:269:9) at emitOne (events.js:77:13) at TLSSocket.emit (events.js:169:7) at emitErrorNT (net.js:1269:8) at nextTickCallbackWith2Args (node.js:442:9) at process._tickDomainCallback (node.js:397:17)​

Après analyse, le problème rencontré sur la plateforme est causé par le proxy qui est en front du serveur.
Comme l’application n’est pas configuré avec les informations du proxy, elle refuse l’échange du token d’authentification et clos le processus.

**Comment by rkouifi** [comment]
L'académie de Guyane n'utilise plus du proxy. Voir si c'est le problème est toujours d'actualité

**Comment by rkouifi** [comment]
Pr réglé par le client 
Charge consommée Witty : 0,5j
Histoire livrée.
