### ISSUE TITLE
lien vers le guide d'utilisation cassé

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#529]
Quand on clique sur le lien "Guide utilisateur" dans le footer la page retourne `Cannot GET /data/User_guide.pdf `

**Comment by SimonSarazin** [comment]
A rajouter par ce lien directement ? : https://github.com/AccessiDys/AccessiDys/raw/master/Guide%20d'utilisation%20AccessiDys_V01.4.pdf

**Comment by SimonSarazin** [comment]
Résolu par Ckiw.
