### ISSUE TITLE
Chargement long à la première visite

### ISSUE THREAD

**Issue by ckiw** [AccessiDys/AccessiDys#534]
L'application n'affiche rien tant que tout les fichiers ne sont pas chargés, notamment le fichier tesseract.js, à voir si on peux résoudre le problème en chargeant ce fichier plus tard

**Comment by SimonSarazin** [comment]
En effet, environ 10s sur une connexion fibre juste pour charger tesseract.js (13,5mb). Avant que le fichier soit chargé, le site ne s'affiche pas. Il s'affiche après chargement de tous les JS, soit 15 secondes, ce qui est énorme lors de la première visite.
@ckiw va voir pour d'abord charger la page d'inscription puis ensuite les JS en fond sans que l'utilisateur s'en rende compte. Aussi, compresser le JS autant que possible.
![selection_010](https://cloud.githubusercontent.com/assets/620174/21650442/4798ef0c-d2a5-11e6-99d1-68138e97fb77.png)

**Comment by ckiw** [comment]
#535

**Comment by ckiw** [comment]
réglé avec l'attribut async sur le javascript
