### ISSUE TITLE
Clic sur le logo ne renvoie pas à l’accueil

### ISSUE THREAD

**Issue by rkouifi** [AccessiDys/AccessiDys#538]
le clic sur le logo doit renvoyer à l’accueil de l'application.
après connexion la page accueil est la page de liste des docs - ajouter un bouton "Maison"  ?
Quand on survole le logo, on lit infobule "CNED", il faut lire "Retour à l'accueil"

**Comment by rkouifi** [comment]
1) le clic sur le logo doit renvoyer à l’accueil de l'application (Mes documents) ==> OK
2) Quand on survole le logo, on lit infobulle "CNED", il faut lire "Retour à l'accueil" ==> KO : l'infobulle CNED est existe encore.

**Comment by rkouifi** [comment]
Environnement d'integration : PC / Google Chrome
le clic sur le logo doit renvoyer à l’accueil de l'application (Mes documents) ==> OK
Quand on survole le logo, on lit infobulle  "Retour à l'accueil" ==> OK

**Comment by Marithe17** [comment]
Environnement d'integration : PC / Firefoxe
le clic sur le logo doit renvoyer à l’accueil de l'application (Mes documents) ==> OK
Quand on survole le logo, on lit infobulle "Retour à l'accueil" ==> OK
Environnement d'integration : PC / IE
Impossible de monter sur Url : https://accessidys-integration.witty-services.com/
