### ISSUE TITLE
Amélioration de la consultation de documents

### ISSUE THREAD

**Issue by rkouifi** [AccessiDys/AccessiDys#543]
Consultation de documents :Amélioration les folios / navigation de pages  - page 1/x et icones inactifs quand bout de course

**Comment by Marithe17** [comment]
Environnement intégration PC/Google chrome /Firefoxe
-> Le dernier doc modifié en haut de la liste

**Comment by rkouifi** [comment]
En mode de page, le numéro de page commence par zéro !!!

**Comment by Marithe17** [comment]
Numéro de page -> va jusqu'à 2 même si il n'y a qu'1 page

**Comment by rkouifi** [comment]
A Marithe17: Je pense quand il affiche le sommaire, il le considère comme une page à part entière. ce qui explique pourquoi tu te trouves 2 pages au lieu d'une.

**Comment by rkouifi** [comment]
Démo : Non réalisé car l'édition d'un document avec plusieurs pages n'était pas possible.
