### ISSUE TITLE
Aperçu des profils : Réglage de l'aperçu des styles en nombre de caractères

### ISSUE THREAD

**Issue by rkouifi** [AccessiDys/AccessiDys#545]
Aperçu des profils : Réglage de l'aperçu des styles en nombre de caractères.
Voir la possibilité d'intégrer le texte dans un fichier de configuration

**Comment by Marithe17** [comment]
Environnement intégration -> PC/Google Chrome/Firefoxe
Prewiew Titre 1/Titre2/Titre3/Titre4 / Paragraphe -> OK 
Manque les autres styles

**Comment by rkouifi** [comment]
Les autres styles sont à ajouter dans le compte administrateur pour qu'ils apparaissent lors de la création de profil.
