### ISSUE TITLE
Remplacer "Bookmarklet" par "Web adapté"

### ISSUE THREAD

**Issue by rkouifi** [AccessiDys/AccessiDys#548]
Menu : Remplacer "Bookmarklet" par "Web adapté" / modifier le pictot.

**Comment by rkouifi** [comment]
test dans l'Environnement d'intégration : 
1) Mettre à jour le Picot  ( pour que le web et document soient reconnus par l'utilisateur)
2) Remplacer "VOTRE BOOKMARKLET" par "WEB ADAPTE"
3) Remplacer "Glissez le bouton Accessidys sur la barre de favoris de votre navigateur (située en haut de l’écran) afin de faciliter …lancer automatiquement l’affichage adapté de vos documents" par "Glissez le bouton Accessidys sur la barre de favoris de votre navigateur (située en haut de l’écran). Il vous permettra l’affichage adapté de vos documents web"

**Comment by rkouifi** [comment]
L'infobulle de "Web adapté" est "Bookmarklet" !!! merci de mettre "Web adapté"

**Comment by Marithe17** [comment]
NB : Il vous permettra l’affichage adapté de vos documents web dans l'application.
