### ISSUE TITLE
Améliorer le format de la date

### ISSUE THREAD

**Issue by rkouifi** [AccessiDys/AccessiDys#565]
Le format de la date doit être affiché en fonction de la langue de l'application.

**Comment by Marithe17** [comment]
Environnement PC/Google Chrome/Firefoxe
OK

**Comment by rkouifi** [comment]
Ok pour le format français. Reste à tester le format anglo-saxon.
Corentin : Le format de date dépend du navigateur ? de l'OS ou de la langue des interfaces AccessiDys?
