### ISSUE TITLE
Intégrer la fonctionnalité « profil actuel » dans la page consultation de document

### ISSUE THREAD

**Issue by rkouifi** [AccessiDys/AccessiDys#569]
Intégrer la fonctionnalité « profil actuel » qui est dans le menu de navigation de la page consultation de document.
remplacer par header fixe permettant de voir la ligne logo - profil actuel - menu

**Comment by Marithe17** [comment]
Environnement d'integration : PC / Google Chrome/Firefoxe -> Header fixe et responsive
