### ISSUE TITLE
Pas de titre dans document

### ISSUE THREAD

**Issue by rkouifi** [AccessiDys/AccessiDys#574]
quand on affiche le fichier qui s'appelle toto.doc, je m'attends à voir en haut de la page de contenu le titre du document "TOTO" afin de savoir dans quel document je me trouve ou un fil d'ariane.
Idem dans le cas d'une page web (récupérer le contenu de la balise TITLE et l'afficher en haut du document).

**Comment by rkouifi** [comment]
Il sera en haut quand le sommaire sera supprimé de la page.

**Comment by rkouifi** [comment]
Environnement d'intégration
1) Les images ne sont pas affichées dans le document
2) La bookmarklet ne  fonctionne pas

**Comment by Marithe17** [comment]
Environnement intégration -> PC / Google Chrome / Firefoxe
Le web adapté fonctionne - > Par contre très grosse lenteur 
    -> les images ne s''affichent pas mais la balise visible dans le texte  `` <img>
    -> impossible d'enregistrer le doc

**Comment by rkouifi** [comment]
Dans la navigation adapté, afficher le bon title
