### ISSUE TITLE
Editeur de textes : Ajout message après enregistrement

### ISSUE THREAD

**Issue by rkouifi** [AccessiDys/AccessiDys#577]
Ce que j'observe  :  Après enregistrement de document, pas de message
Ce que j'attends : Après enregistrement de document, affichage d'un message qui apparaît quelques secondes

**Comment by Marithe17** [comment]
Environnement intégration PC/Google Chrome/Firefoxe
            ->Enregistrement signalé (aussi bien profil que doc)
