### ISSUE TITLE
Etude : étendre la fonctionnalité de la bookmarklet

### ISSUE THREAD

**Issue by rkouifi** [AccessiDys/AccessiDys#602]
En tant que client du Cned
 je peux afficher le contenu de Moodle  et Dcol dans AccessiDys. 
afin de le rendre accessible

**Comment by Marithe17** [comment]
La DSI se rapprochera d'Alexis pour lui fournir les indications

**Comment by Marithe17** [comment]
Réunion le 24/10 avec la DSI et les développeurs de Moodle Cned pour leur expliquer notre besoin.
