### ISSUE TITLE
Affichage des profils

### ISSUE THREAD

**Issue by Marithe17** [AccessiDys/AccessiDys#645]
En tant qu'utilisateur je ne veux voir en affichage dans la page profil que le profil accessidys par défault , 
les autres profils par défaut sont dans la liste déroulante mais pas en aperçu.

**Comment by Marithe17** [comment]
Contre ordre : 
On laisse l'affichage des profils par défaut sur la page profil car nous avons la fonction dupliquer le profil.
Par contre il faudrait que le profil créé (donc nouveau profil), apparaisse en haut de la liste (et non en bas comme actuellement)
Serait il possibilité d'ajouter la fonction dupliquer sur un profil créé?

**Comment by rkouifi** [comment]
ça marche avec Google Chrome
