### ISSUE TITLE
Dupliquer les styles d'un profil à partir d'un style

### ISSUE THREAD

**Issue by rkouifi** [AccessiDys/AccessiDys#660]
-	Simplifier la saisie de styles : proposer un style général qui s’appliquera à tous les styles. 
Avec la possibilité de modifier ponctuellement chacun des styles.

Ajouter dans l'interface "Modifier les valeurs d'un style" de tous les styles
"Affecter à tous les styles" : A cocher par défaut c'est décoché

**Comment by Marithe17** [comment]
Fonction fait sur le sprint3 de Witty
