### ISSUE TITLE
 Fonctionnement AccessiDys sans internet

### ISSUE THREAD

**Issue by rkouifi** [AccessiDys/AccessiDys#662]
Ce que j'observe :Après avoir ouvert AccessiDys depuis un navigateur et avec une connexion internet, si je ferme le navigateur et que je n'ai plus internet je ne peux plus travailler sur accessidys, je n'y accède plus.

Ce qu'il faudrait : continuer à utiliser accessidys même après fermeture du navigateur et coupure internet, en mode déconnecté.

(Fonctionnement AccessiDys sans internet après ouverture d'AccessiDys dans un navigateur et fermeture avec possibilité de synchroniser les documents (après connexion internet).

**Comment by Marithe17** [comment]
Après rajout d'accessidys dans mes favoris ou après fermeture de l'onglet je veux pouvoir accesseder à Accesidys hors connexion (internet)
