### ISSUE TITLE
Message cookies

### ISSUE THREAD

**Issue by rkouifi** [AccessiDys/AccessiDys#672]
Message précisant que nous collectons les données personnelles (stockage de documents et profils dans le cache).

Exemple de message:
"Vos documents et vos profils seront sauvegardés dans le cache du navigateur web que vous utilisez.
En naviguant sur AccessiDys, vous acceptez l’utilisation des cookies. Nous nous en servons pour comptabiliser nos visiteurs. Plus d'informations: clique ici"
**Fermer**

https://opt-out.ferank.eu/fr/

http://www.cookiechoices.org/
https://www.cnil.fr/fr/site-web-cookies-et-autres-traceurs

**Comment by DI-access** [comment]
attention la notion de publicité pourrait faire croire que nous affichons des pubs ce qui n'est pas le cas. Exemple de message plus approprié : …sur le site Fun c’est écrit comme ceci :
En poursuivant votre navigation sur le site fun-mooc.fr, vous acceptez l'utilisation de cookies permettant d'améliorer votre expérience utilisateur. 
> En savoir plus

**Comment by Marithe17** [comment]
Remplacer par : 
En poursuivant votre navigation sur ce site, vous acceptez l'utilisation de cookies permettant d'améliorer votre expérience utilisateur.
