### ISSUE TITLE
Avec Fire Fox: accès à l'ancienne version accessiDys

### ISSUE THREAD

**Issue by rkouifi** [AccessiDys/AccessiDys#678]
Avec FireFox, J'accède à l'ancienne version d'AccessiDys
![image](https://user-images.githubusercontent.com/24315542/28661105-e449dfcc-72b5-11e7-8de7-8c858e6670d0.png)

**Comment by Marithe17** [comment]
Test fait sur 3 ordi différent et sur navigation privée -> nouvelle version
