### ISSUE TITLE
Bug - synthèse vocale anglais par défaut sans les autres langues

### ISSUE THREAD

**Issue by DI-access** [AccessiDys/AccessiDys#682]
Sur firefox version 52.3.0 la synthèse vocale est par défaut en anglais.
Dans mes profils, la liste déroulante ne propose que l'anglais

Idem sur Chrome

Retour d'expérience d'un collège, Mme Claverie

**Comment by Marithe17** [comment]
Dans paramètre de la synthèse vocale, il faut la langue Française par défaut (le menu déroulant) ,
car si nous laissons le champ blanc (1er item) la synthèse vocale est en anglais
