### ISSUE TITLE
Sauvegarde nextcloud académique

### ISSUE THREAD

**Issue by ljoets** [AccessiDys/AccessiDys#685]
Bonjour,
L'académie de Versailles propose aux enseignants un espace de stockage en ligne basé sur Nextcloud : http://edu-nuage.ac-versailles.fr Je ne peux me résoudre à suggérer à des élèves de stocker des cours ou documents perso sur dropbox. Est-il envisageable de pouvoir stocker ses sauvegardes sur un stockage type nexcloud ?
Merci

**Comment by Marithe17** [comment]
Bonjour,
Très prochainement vous aurez la possibilité de sauvegarder vos documents sur Google Drive et Onedrive en plus de dropbox.  Nous allons étudier votre demande. 
Merci de votre retour

**Comment by ljoets** [comment]
Merci pour votre réponse.
Cependant, dans le milieu éducatif, onedrive et googledrive sont à mon avis autant à proscrire que dropbox du point de vue du respect des données de l'utilisateurs ;-)
C'est pour cette raison que je suggère un conecteur générique à un partage webdav par exemple.
Quoi qu'il en soit, bravo pour le travail ;-)

**Comment by Marithe17** [comment]
Nous avions prévu un déploiement (installation) au sein des académies, ce qui pouvait résoudre votre problématique.
Mais à l'instant t nous sommes en attente de décisions des hiérarchies.
Je vous conseille fortement de faire une demande à la DNE.

**Comment by ljoets** [comment]
Merci pour votre retour.
J'enseigne dans l'académie de Versailles, et je voulais justement leur proposer d'héberger ce service.
Je les contacte donc ;-)

**Comment by ckiw** [comment]
Il y a cette tache dont je me charge #585 
Je pourrais jeter un oeil en ce qui concerne nextcloud au passage et je reviens vers vous.
